project:
  type: website

website:
  title: "Atika Syeda"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - publications.qmd 
      - software.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true